### PR TITLE
Old windowsy design maybe

### PR DESCRIPTION
**Pull request by tholman**
# whats happening
- removes old posts that are a few lines of text (sadly has to be done I think, since they kinda mangle the designs ... but maybe not)
- Design changes and layout changes

# todo
- Logo/Header ... I was thinking maybe something like a desktop icon https://cdn.shopify.com/s/files/1/2128/8929/files/windows_95_icons_globe_large.jpg?v=1578343419 for logo and something oldy for RSS/github etc
- pagination
- move the duplicate article code into a single partial, not duplicated 3 times
- maybe a better way to "read more" 
- probably need that cool old windows scrollbar at the side of them
- mobile
- maybe allow items to be X'd and minimized and dragged around

# thoughts
- will find a way to bring back images to posts managed through not git ideally
- perhaps images get some treatment to fit in with the design
- the stagger of the bottom posts is with the idea that something can sit horizontal to them like a icon to https://winmine-exe.now.sh/ etc

### CODE REVIEW

**Comment by JohJakob** [comment]
I see you’re working on a redesign! I’ll take a closer look at it and comment some thoughts here.

**Comment by tholman** [comment]
🙏 yeah let me know what you think! This working branch is up here https://theindieweb.com/ ... so you can get the general feel 👯

**Comment by TJScalzo** [comment]
My first thought when looking at this design is the lack of font smoothing with the chosen font makes it difficult to read bold text at smaller resolutions. It might have something to do with the way the secondary windows are offset from the center, but the letters blend together and readability is decreased.
Screen Shot 2020-06-14 at 6 01 04 PM
Maybe a font that's designed without the need for font smoothing/anti-aliasing would be helpful?

**Comment by TJScalzo** [comment]
Also... **Idea:** A maximize button in each article's header could be used to open the full article instead of, or in addition to, the read-more text at the end of the blurb.

**Comment by tholman** [comment]
lol wow safari treats it so much more painfully to chrome haha 🗡️

**Comment by tholman** [comment]
ahh, its not liking the monospace font for some reason

**Comment by TJScalzo** [comment]
> lol wow safari treats it so much more painfully to chrome haha 🗡️

Interesting... In Chrome it looks like a properly pixellated, "Windowsy" font. But in Firefox it looks like it's smoothing the font normally. Like you said, Safari has a lot of trouble with the font with font-smoothing turned off. I'm not sure how to get consistency between browsers in this case...

**Comment by tholman** [comment]
the hunt for a pixely font or two begins, i guess. `font-family: monospace, Courier New;` isn't too bad for me either, or at least less bad.

**Comment by tholman** [comment]
> Also... **Idea:** A maximize button in each article's header could be used to open the full article instead of, or in addition to, the read-more text at the end of the blurb.

I was thinking maybe I'll try and make all of these functional in one way or another & maybe draggable windows. haha would be a nice touch

**Comment by tholman** [comment]
Did some safari hacks for now, and just turned it off on some h1's 🗡️ 

Can't really find a font online that fits the need, tho would be happy to pay for one if you spy anything neat. little nicer as it goes, and am kinda happy to have it a little different for each different browser at the end of the day. haha firefox doesn't even support destroying ur font rendering at all :)

**Comment by JohJakob** [comment]
The new design looks nice so far, even though I’m not the biggest fan of the retro Windows interface design.

Some suggestions for improving the design:

- use the sans-serif font in the window title bar as well
- the shadows are a bit to light in my opinion, maybe they could have a more coarse dithering pattern w/o the semi-transparent box
- make the window buttons more “blocky” (like the original buttons in Windows) and maybe add functionality → closing the window would not make sense, but the “maximize” button could make the window larger (should be possible using only CSS) and overlay the others (+ dithered background to darken everything around the window for better focus)

I’ll experiment with this stuff a bit. Should I create a pull request to your [th/maybe-this branch](https://github.com/tholman/the-indie-web/tree/th/maybe-this)?

**Comment by tholman** [comment]
A few of these decisions were intentionally that way, like the monospaced header... ive got a little vaporwave mood board I'll share 👯

**Pull request merged**
